# Install extension: REST Client 
### login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "UserName": "admin",
  "Password": "admin"
}

### USER
# Get
GET http://localhost:5000/odata/users
Accept: application/json;
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzIzNDMzODYwLCJleHAiOjE3MjQwMzg2NjAsImlhdCI6MTcyMzQzMzg2MCwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI4OS8iLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3Mjg5LyJ9.oHn-0TtmoSwoIt8J2rweOPuTU5qzvEa0MZIjE4nEmc4
###

# Get
GET http://localhost:5000/odata/Users
Accept: application/json;
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzIzNDMzODYwLCJleHAiOjE3MjQwMzg2NjAsImlhdCI6MTcyMzQzMzg2MCwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI4OS8iLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3Mjg5LyJ9.oHn-0TtmoSwoIt8J2rweOPuTU5qzvEa0MZIjE4nEmc4
###

# Create
POST http://localhost:5000/odata/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzIzNDMzODYwLCJleHAiOjE3MjQwMzg2NjAsImlhdCI6MTcyMzQzMzg2MCwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI4OS8iLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3Mjg5LyJ9.oHn-0TtmoSwoIt8J2rweOPuTU5qzvEa0MZIjE4nEmc4

{
  "FullName": "abc"
}
###

# GET by id
GET http://localhost:5000/odata/users(3)
Accept: application/json;
###

# Update
PATCH http://localhost:5000/odata/users(2)
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzIzNDMzODYwLCJleHAiOjE3MjQwMzg2NjAsImlhdCI6MTcyMzQzMzg2MCwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI4OS8iLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3Mjg5LyJ9.oHn-0TtmoSwoIt8J2rweOPuTU5qzvEa0MZIjE4nEmc4

{
  "IsActive": true
}
